import { ArrowUpRight, BriefcaseBusiness, ChevronRight, CircleDollarSign, Landmark, TrendingUp, WalletCards } from 'lucide-react';
import { properties } from '../data/properties';
import { formatINR, formatPercent } from '../lib/format';
import { Badge, Button, Card } from '../components/ui';

const holdings = [];

const walletBalance = 0;

export function Dashboard() {
  if (!holdings.length) return <main className="mx-auto max-w-7xl px-5 pb-20 pt-10 lg:px-8"><EmptyPortfolio /></main>;

  const totalInvested = holdings.reduce((sum, holding) => sum + holding.invested, 0);
  const currentValue = holdings.reduce((sum, holding) => sum + holding.currentValue, 0);
  const returns = currentValue - totalInvested;
  const allocationTotal = holdings.reduce((sum, holding) => sum + holding.currentValue, 0);

  return <main className="mx-auto max-w-7xl px-5 pb-20 pt-10 lg:px-8"><PageHeading /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard icon={BriefcaseBusiness} label="Total invested" value={formatINR(totalInvested)} detail="Across 3 properties" /><KpiCard icon={TrendingUp} label="Current portfolio value" value={formatINR(currentValue)} detail="Updated just now" accent="green" /><KpiCard icon={CircleDollarSign} label="Total returns (ROI)" value={formatINR(returns)} detail={`${formatPercent((returns / totalInvested) * 100)} all time`} accent="green" /><KpiCard icon={WalletCards} label="Wallet balance" value={formatINR(walletBalance)} detail="Ready to invest" /></section><div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-line px-5 py-5 sm:px-6"><div><h2 className="font-display text-lg font-bold text-ink">Your portfolio</h2><p className="mt-1 text-sm text-slate-500">Track your fractional property holdings.</p></div><a href="/properties" className="hidden items-center gap-1 text-sm font-bold text-forest sm:flex">Explore properties <ArrowUpRight size={15} /></a></div><PortfolioTable /></Card><AllocationCard holdings={holdings} total={allocationTotal} /></div></main>;
}

function PageHeading() { return <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-forest">Investor overview</p><h1 className="font-display text-3xl font-bold tracking-tight text-ink sm:text-4xl">Good morning, Arjun.</h1><p className="mt-2 text-sm text-slate-500">Here is how your real estate portfolio is performing.</p></div><Button variant="outline" onClick={() => { window.location.href = '/properties'; }}>Browse opportunities <ArrowUpRight size={16} /></Button></div>; }
function KpiCard({ icon: Icon, label, value, detail, accent }) { return <Card className="p-5"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${accent === 'green' ? 'bg-emerald-50 text-forest' : 'bg-slate-100 text-ink'}`}><Icon size={19} /></div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 font-display text-2xl font-bold text-ink">{value}</p><p className="mt-2 text-xs font-semibold text-slate-500">{detail}</p></Card>; }
function PortfolioTable() { return <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-mist text-[10px] uppercase tracking-wider text-slate-400"><tr>{['Property name', 'Units owned', 'Ownership', 'Invested amount', 'Current est. value', 'ROI', 'Status'].map((heading) => <th key={heading} className="px-5 py-3 font-bold sm:px-6">{heading}</th>)}</tr></thead><tbody className="divide-y divide-line">{holdings.map((holding) => { const property = properties.find((item) => item.id === holding.propertyId); return <tr key={holding.propertyId} className="group hover:bg-mist/60"><td className="px-5 py-4 sm:px-6"><a href={`/properties/${property.id}`} className="font-bold text-ink hover:text-forest">{property.title}</a><p className="mt-1 text-xs text-slate-400">{property.city}, {property.state}</p></td><td className="px-5 py-4 text-slate-600 sm:px-6">{holding.units}</td><td className="px-5 py-4 text-slate-600 sm:px-6">{formatPercent((holding.units / property.totalUnits) * 100)}</td><td className="px-5 py-4 font-semibold text-ink sm:px-6">{formatINR(holding.invested)}</td><td className="px-5 py-4 font-semibold text-ink sm:px-6">{formatINR(holding.currentValue)}</td><td className="px-5 py-4 font-bold text-forest sm:px-6">+{formatPercent(holding.roi)}</td><td className="px-5 py-4 sm:px-6"><Badge tone={holding.status === 'FUNDED' ? 'funded' : 'live'}>{holding.status}</Badge></td></tr>; })}</tbody></table></div>; }
function AllocationCard({ holdings: portfolio, total }) { return <Card className="p-6"><div className="flex items-start justify-between"><div><h2 className="font-display text-lg font-bold text-ink">Allocation</h2><p className="mt-1 text-sm text-slate-500">By current value</p></div><Landmark size={19} className="text-forest" /></div><div className="mx-auto my-8 flex h-44 w-44 items-center justify-center rounded-full" style={{ background: `conic-gradient(#157a6e 0 45%, #1e9b8c 45% 77%, #b9ded5 77% 100%)` }}><div className="flex h-28 w-28 flex-col items-center justify-center rounded-full bg-white"><span className="text-xs text-slate-400">Portfolio</span><span className="mt-1 text-sm font-bold text-ink">100%</span></div></div><div className="space-y-4">{portfolio.map((holding, index) => { const property = properties.find((item) => item.id === holding.propertyId); const colors = ['bg-forest', 'bg-[#1e9b8c]', 'bg-[#b9ded5]']; return <div key={holding.propertyId} className="flex items-center justify-between gap-3 text-sm"><div className="flex min-w-0 items-center gap-2"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${colors[index]}`} /><span className="truncate text-slate-600">{property.title}</span></div><span className="font-bold text-ink">{formatPercent((holding.currentValue / total) * 100)}</span></div>; })}</div></Card>; }

export function EmptyPortfolio() { return <Card className="mx-auto max-w-xl p-10 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-50 text-forest"><BriefcaseBusiness size={24} /></div><h2 className="mt-5 font-display text-xl font-bold text-ink">Your portfolio is ready for its first asset</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">Explore curated opportunities and start building a property portfolio one unit at a time.</p><Button className="mt-6" onClick={() => { window.location.href = '/properties'; }}>Explore marketplace <ChevronRight size={16} /></Button></Card>; }
