import { useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, CalendarDays, CheckCircle2, Plus, WalletCards, X } from 'lucide-react';
import { formatINR } from '../lib/format';
import { Badge, Button, Card, Input } from '../components/ui';

const transactions = [];

export function Wallet() {
  const [modalOpen, setModalOpen] = useState(false);
  const [amount, setAmount] = useState('25000');
  const [balance, setBalance] = useState(0);
  const [notice, setNotice] = useState(false);
  const submitTopup = (event) => { event.preventDefault(); const value = Number(amount); if (!value || value < 100) return; setBalance((current) => current + value * 100); setModalOpen(false); setNotice(true); setTimeout(() => setNotice(false), 3500); };
  return <main className="mx-auto max-w-7xl px-5 pb-20 pt-10 lg:px-8"><div className="mb-8"><p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-forest">Cash management</p><h1 className="font-display text-3xl font-bold tracking-tight text-ink sm:text-4xl">Wallet</h1><p className="mt-2 text-sm text-slate-500">Manage funds for your next investment.</p></div><Card className="overflow-hidden bg-ink text-white"><div className="grid gap-8 p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2 text-sm font-semibold text-emerald-200"><WalletCards size={17} />Available to invest</div><p className="mt-4 font-display text-4xl font-bold tracking-tight">{formatINR(balance)}</p><p className="mt-2 text-sm text-slate-300">Your balance is held securely in your investment wallet.</p></div><Button className="w-full bg-white text-ink hover:bg-emerald-50 sm:w-auto" onClick={() => setModalOpen(true)}><Plus size={17} /> Add money</Button></div></Card>{notice && <div className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><CheckCircle2 size={17} />Money added successfully. Your balance is ready to use.</div>}<Card className="mt-8 overflow-hidden"><div className="border-b border-line px-5 py-5 sm:px-6"><h2 className="font-display text-lg font-bold text-ink">Transaction ledger</h2><p className="mt-1 text-sm text-slate-500">A clear record of every wallet movement.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-mist text-[10px] uppercase tracking-wider text-slate-400"><tr>{['Date', 'Type', 'Description', 'Amount', 'Status'].map((heading) => <th key={heading} className="px-5 py-3 font-bold sm:px-6">{heading}</th>)}</tr></thead><tbody className="divide-y divide-line">{transactions.map((transaction) => <tr key={transaction.id}><td className="px-5 py-4 text-slate-500 sm:px-6"><span className="flex items-center gap-2"><CalendarDays size={14} />{transaction.date}</span></td><td className="px-5 py-4 sm:px-6"><span className={`inline-flex rounded-lg px-2.5 py-1 text-[10px] font-bold tracking-wider ${transaction.type === 'TOPUP' ? 'bg-emerald-50 text-emerald-700' : transaction.type === 'PAYOUT' ? 'bg-blue-50 text-blue-700' : 'bg-slate-100 text-slate-600'}`}>{transaction.type}</span></td><td className="px-5 py-4 font-semibold text-ink sm:px-6">{transaction.description}</td><td className={`px-5 py-4 font-bold sm:px-6 ${transaction.amount > 0 ? 'text-forest' : 'text-ink'}`}>{transaction.amount > 0 ? '+' : ''}{formatINR(transaction.amount)}</td><td className="px-5 py-4 sm:px-6"><Badge tone="funded">{transaction.status}</Badge></td></tr>)}</tbody></table></div></Card>{modalOpen && <TopupModal amount={amount} setAmount={setAmount} onClose={() => setModalOpen(false)} onSubmit={submitTopup} />}</main>;
}

function TopupModal({ amount, setAmount, onClose, onSubmit }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/40 p-5 backdrop-blur-sm"><Card className="w-full max-w-md p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="font-display text-xl font-bold text-ink">Add money to wallet</h2><p className="mt-1 text-sm text-slate-500">Enter an amount in Indian rupees.</p></div><button onClick={onClose} aria-label="Close modal" className="rounded-lg p-2 text-slate-400 hover:bg-mist hover:text-ink"><X size={18} /></button></div><form onSubmit={onSubmit} className="mt-6"><label className="text-xs font-bold uppercase tracking-wider text-slate-500">Amount</label><div className="relative mt-2"><span className="absolute left-3.5 top-3 text-slate-500">₹</span><Input autoFocus type="number" min="100" step="100" value={amount} onChange={(event) => setAmount(event.target.value)} className="pl-8 text-lg font-bold" /></div><div className="mt-5 flex gap-3"><Button type="button" variant="outline" className="flex-1" onClick={onClose}>Cancel</Button><Button type="submit" className="flex-1"><ArrowUpRight size={16} /> Add money</Button></div></form></Card></div>; }
